### ISSUE TITLE
parallel run

### ISSUE THREAD

**Issue by Gabbyr** [jenkinsci/coordinator-plugin#16]
trying to run 2 jobs in parallel, but somehow I get it in serial mode all the time..jobs are sibling, not parent-child. am I doing something wrong here ?

**Comment by Gabbyr** [comment]
nm - got it. missed the p and s notation for parallel and serial....:-)

**Comment by ace-han** [comment]
Glad that you figured it out.

**Comment by Gabbyr** [comment]
Ace - one more thing, if I may - it would be great if the parameters of the
any child jobs are exposed to the root job. that way I can see and change
them if I wish to run it manually from the execution plan page.also - I am
not able to visually track the execution at it happens from the root top
page.

Thanks,

Gabby.

**Comment by ace-han** [comment]
@Gabbyr  your requirement could be consolidated as below points:
1. child jobs' params could be seen from coordinator job
2. coordinator job could track down the execution progress in one place

# Point 2
one of the goal of `coordinator-plugin` is to track down all relevant jobs in one page, like below in each building page:

![image](https://cloud.githubusercontent.com/assets/1177332/11892718/ce5696da-a5a5-11e5-9803-064e7753a459.png)

if above demo graph is not helping you, then I don't get what you mean by `visually track the execution at it happens from the root top`, please add more description about that

# Point 1
Since I have taken advantage of the existing component provided by jenkins itself shown as below. However, it requires you one more click to see what's the config about the child job at your desire(I think it temporarily the only solution to your problem for the time being)
![image](https://cloud.githubusercontent.com/assets/1177332/11893075/86b8eaa0-a5a8-11e5-8641-158a9ee2dbee.png)


Considering I don't have an appropriate ui prototype to elegantly support this, I will hold back on this requirement and keep this in mind to see if any idea awesome pops out. 
Or if any sparking ui prototype about this requirement hits you, you could open a new feature request on this github( like #6 with a demo snapshot will be better). I will appreciate that!

**Comment by Gabbyr** [comment]
Thanks a lot Ace.

The thing is that from some reason, I don't see that page you are showing
below,with the child jobs running progress bar. what am I missing here. .?

**Comment by ace-han** [comment]
Plz check out that 
* if you chlid jobs ends quickly, not running long enough to see its progress bar
* after trigger a new build, plz go to url 
`http://$JENKINSHOST:$PORT/view/All/job/$JOB_NAME/$BUILD_NUMBER/`
like: http://jenkins.unendedquest.com/view/All/job/simple_demo/28/

or just click from build number in `build history` as below

![image](https://cloud.githubusercontent.com/assets/1177332/11894076/c2c7f89a-a5af-11e5-87d4-4f753be8fb62.png)
