### ISSUE TITLE
Create a Dockerfile for the project

### ISSUE THREAD

**Issue by kymair** [jenkinsci/coordinator-plugin#19]
Should create a Dockerfile to allow fast development env build up. 

Basically the image should
1. Install Java, Maven, Jenkins;
1. Grab latest coordinator plugin with sample jobs;
1. Run Jenkins, open necessary port for debugging.

**Comment by kymair** [comment]
I was wrong. After checkout the project in IntelliJ, invoking a single Maven command can load up the full Jenkins development env. A docker is not only unnecessary but also slows things down due to virtualization.

**Comment by ace-han** [comment]
`docker` might not be necessary, however the `jobs` folder in `work` folder, I think, is necessary. 

Not only for test purpose but also a quick start for new comer on this project. 
This `jobs` should contain few  classical scenarios job configuration only (to be more specific...)

![image](https://cloud.githubusercontent.com/assets/1177332/13028563/8f132b98-d2ad-11e5-8d75-365c030fffd4.png)

**Comment by Max-Serra** [comment]
Hi guys,

I'm setting up a development environment to better contribute to this project. I'm reading the wiki regarding how to setup Plugin development, but there are several possibilities and I know how much time consuming can be each Maven build.

The jenkins setup I'm using is already complex and this complexity is growing since we use distributed builds over slaves both Linux and Windows. I guess that setup is able to stress a lot the Coordinator jobs, maybe covering scenarios which can cause particular side effects that I would like to investigate deeply.

For this reason I need to replicate the linux jenkins production environment in my local windows development environment. Is the setup in the screenshot, created just running the maven commands mentioned here https://wiki.jenkins-ci.org/display/JENKINS/Plugin+tutorial#Plugintutorial-Eclipse ? Which is the maven command you are talking about?

In that page is described how to start a new project, but it is not so clear how to setup a plugin to contribute to. Do you have any suggestion?

**Comment by kymair** [comment]
@Max-Serra I've just setup the env several days before. Looks straightforward enough. I just cloned the source code, imported into IntelliJ, and run following maven command (which is mentioned in project root `mvn_scripts.txt`)

    hpi:run -Djetty.port=8090 -Dhpi.prefix=/jenkins
    
![image](https://cloud.githubusercontent.com/assets/130247/13314993/1807fa6c-dbe3-11e5-858d-abc5ce40f6d4.png)

**Comment by Max-Serra** [comment]
Thanks Jindi, I was just watching that file and indetifying the right mvn command.  I'm using Eclipse...I gave a look long time ago to Intellij, but I didn't yet really use. I see error in the project pom... it seems not correctly linking parent pom...in your workspace there is jenkins project...is it just the folder containing jenkins pom or?  In my workspace I didn't yet link any jenkins reference.

**Comment by kymair** [comment]
No the Jenkins source is cloned separately, no need for plugin development.
I checked it out just for my curiosity.

Best Regards
Kymair Wu
