### ISSUE TITLE
Failure on triggering multi-configuration project as atomic job

### ISSUE THREAD

**Issue by Alren-huang** [jenkinsci/coordinator-plugin#32]
As titled 

status is nothing as follow:
![image](https://cloud.githubusercontent.com/assets/4769275/14759717/9e603e5a-095e-11e6-8f47-d848c171b1b3.png)

multi-configuration project's ${JOB_NAME} is different from freestyle project, may be is the key

![image](https://cloud.githubusercontent.com/assets/4769275/14759710/730921e0-095e-11e6-811c-4d8bf86370f5.png)

**Comment by ace-han** [comment]
Hello there, 

Yes, I confirmed this is actual an issue. 

However, a work around solution is:
* replace `multi-configuration project` to `freestyle project`
* install https://wiki.jenkins-ci.org/display/JENKINS/NodeLabel+Parameter+Plugin

And I will schedule to fix this issue in version `1.2.1`

**Comment by ace-han** [comment]
@Alren-huang After a detail looking into this issue, I've decided not to support this `multi-configuration` type of job for the time being.

Please try https://wiki.jenkins-ci.org/display/JENKINS/NodeLabel+Parameter+Plugin instead. Since it will compromise a lot in our current code structure.

Do feel free to raise it out if this is a great violation to you

**Comment by ace-han** [comment]
sth wrong in cglib which requires complicated debug process...
