### ISSUE TITLE
Coordinator Does Not Work with Folders Plugin

### ISSUE THREAD

**Issue by codepoet80** [jenkinsci/coordinator-plugin#34]
If a job is located within a Folder, Coordinator will fail to find the job.
Folders are enabled with this plugin:
https://www.cloudbees.com/products/cloudbees-jenkins-platform/team-edition/features/folders-plugin

**Comment by ace-han** [comment]
I will look into this kind of issues these days. In the mean time, please use other view plugin instead.

**Comment by ace-han** [comment]
As I looked into this issue, there came the problem is that.

What if you have multiple folders(say `folder1` and `folder2`) defined and all have a job in them named `test_1`, and you create an atomic job in `coordinator` project, how do we identify which `test1` you are referring to?

I would suggest the atomic job name in `coordinator` project should go with `item`'s `fullname`. In this way, we are regarding jenkins native way.
naming pattern in `coordinator` executionPlan:

`jenkins.model.Jenkins#getItemByFullName` => `folder_name1/folder_name2/.../project_name`
e.g.:
`folder/job_1`, `folder_1/folder_2/job_2` => in configuring `coordinator job`
`job_1` (not `folder/job_1`) under `folder`
`job_2` (not `folder_1/folder_2/job_2`) under `folder_2` which is also under `folder_1`

a snapshot looks like below
naming in `coordinator`
![image](https://cloud.githubusercontent.com/assets/1177332/15986097/b259e682-3031-11e6-8e73-9e465ecf0bac.png)

naming in `folder plugin`
![image](https://cloud.githubusercontent.com/assets/1177332/15986109/2ef295fe-3032-11e6-99f1-15224e1aabf2.png)

**Comment by negmos** [comment]
Is there a release date for this?

**Comment by ace-han** [comment]
@negmos this problem is fixed in #40, sorry for being vanished for a long long time. 😄
