### ISSUE TITLE
Couldn't pass the parameters with "Extended Choice Parameter" to the downstream job in Jenkins v2.32.1

### ISSUE THREAD

**Issue by BNUZ-YLSY** [jenkinsci/coordinator-plugin#46]
Environment:
- Centos 7
- Docker 1.11.2
- Docker image: "jenkins:alpine"(v2.32.1)

I added java option "`-Dhudson.model.ParametersAction.safeParameters=foo,bar,tar`" to start up the Jenkins,  then followed your illustration to set up a "controller" with some jobs (and i'm using plugin "`Extended Choice Parameter`"). When i triggered the "controller" to start a deployment, the "controller" show the below alert, then i found that the parameters in plugin "`Extended Choice Parameter`" could not pass to the downstream jobs. 

> Building on master in workspace /var/jenkins_home/workspace/Controller . FOO Atomic Job( BAR )'s  ParameterDefinition, ( ExtendedChoiceParameterDefinition ), is not supported and its parameter value won't get activated.

**Comment by ace-han** [comment]
Hello there, 

Since `coordinator-plugin` as an **independent** plugin in `Jenkins` world, we should support as many `third-party` plugins as possible without hacking a lot.

`Parameter`-wise plugins may have different ways to generate/get/set their `value`(s), we should find a `standard` way to retrieve `Parameter`'s values (usually `String`, 'Files', etc) or default values.

That is, we finally have decided to only support those `Parameter` which implemented [ParameterDefinition#getDefaultParameterValue](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/ParameterDefinition.java#L220)

This `getDefaultParameterValue` interface was introduced since version 1.253. We take it fairly general and common enough.

If this still bothers you, you can request the author of `Extended Choice Parameter` to support this  `getDefaultParameterValue` interface.

Thx

**Comment by BNUZ-YLSY** [comment]
I found the way to make it work, all fields in `Extended Choice Parameter` expected `description` must to be filled, and all that fields must to be according expected `default`. 
So I suggest that which using this plugin and `Extended Choice Parameter` to use `property` files to keep the whole stream parameters according in the latest version `Extended Choice Parameter`.

Thank for your patience.
